[2020-11-20 23:45:09,758] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_death 2020-11-15T00:00:00+00:00 [queued]>
[2020-11-20 23:45:09,978] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_death 2020-11-15T00:00:00+00:00 [queued]>
[2020-11-20 23:45:09,981] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-11-20 23:45:09,982] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-11-20 23:45:09,992] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-11-20 23:45:10,120] {taskinstance.py:900} INFO - Executing <Task(BashOperator): fetch_covid_daily_death> on 2020-11-15T00:00:00+00:00
[2020-11-20 23:45:10,125] {standard_task_runner.py:53} INFO - Started process 7169 to run task
[2020-11-20 23:45:11,162] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_death 2020-11-15T00:00:00+00:00 [running]> 6600a3f3922a
[2020-11-20 23:45:11,407] {taskinstance.py:1145} ERROR - 'os' is undefined
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 964, in _run_raw_task
    self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1426, in render_templates
    self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 716, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 723, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 752, in render_template
    return jinja_env.from_string(content).render(**context)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'os' is undefined
[2020-11-20 23:45:11,414] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=us_covid_daily_report_pipeline, task_id=fetch_covid_daily_death, execution_date=20201115T000000, start_date=20201120T234509, end_date=20201120T234511
[2020-11-20 23:45:19,491] {logging_mixin.py:112} INFO - [2020-11-20 23:45:19,490] {local_task_job.py:103} INFO - Task exited with return code 1
