[2020-11-20 23:45:14,812] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_recovered 2020-11-19T00:00:00+00:00 [queued]>
[2020-11-20 23:45:14,869] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_recovered 2020-11-19T00:00:00+00:00 [queued]>
[2020-11-20 23:45:14,870] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-11-20 23:45:14,871] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-11-20 23:45:14,872] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-11-20 23:45:14,921] {taskinstance.py:900} INFO - Executing <Task(BashOperator): fetch_covid_daily_recovered> on 2020-11-19T00:00:00+00:00
[2020-11-20 23:45:14,930] {standard_task_runner.py:53} INFO - Started process 7283 to run task
[2020-11-20 23:45:15,213] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_recovered 2020-11-19T00:00:00+00:00 [running]> 6600a3f3922a
[2020-11-20 23:45:15,301] {taskinstance.py:1145} ERROR - 'os' is undefined
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 964, in _run_raw_task
    self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1426, in render_templates
    self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 716, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 723, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 752, in render_template
    return jinja_env.from_string(content).render(**context)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'os' is undefined
[2020-11-20 23:45:15,310] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=us_covid_daily_report_pipeline, task_id=fetch_covid_daily_recovered, execution_date=20201119T000000, start_date=20201120T234514, end_date=20201120T234515
[2020-11-20 23:45:24,759] {logging_mixin.py:112} INFO - [2020-11-20 23:45:24,759] {local_task_job.py:103} INFO - Task exited with return code 1
[2020-11-20 23:55:43,107] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_recovered 2020-11-19T00:00:00+00:00 [queued]>
[2020-11-20 23:55:43,164] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_recovered 2020-11-19T00:00:00+00:00 [queued]>
[2020-11-20 23:55:43,165] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-11-20 23:55:43,166] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-11-20 23:55:43,168] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-11-20 23:55:43,212] {taskinstance.py:900} INFO - Executing <Task(BashOperator): fetch_covid_daily_recovered> on 2020-11-19T00:00:00+00:00
[2020-11-20 23:55:43,220] {standard_task_runner.py:53} INFO - Started process 518 to run task
[2020-11-20 23:55:43,461] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_recovered 2020-11-19T00:00:00+00:00 [running]> 5fdb493b75fa
[2020-11-20 23:55:43,545] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2020-11-20 23:55:43,549] {bash_operator.py:105} INFO - Temporary script location: /tmp/airflowtmp0a42grxp/fetch_covid_daily_recoveredaorsz7o2
[2020-11-20 23:55:43,549] {bash_operator.py:115} INFO - Running command: curl -o /opt/airflow/data/recovered_20201119.json         --request GET 	    --url https://covid1910.p.rapidapi.com/data/confirmed/province/date/11-19-2020 	    --header 'x-rapidapi-host: covid1910.p.rapidapi.com' 	    --header 'x-rapidapi-key: None'
[2020-11-20 23:55:43,558] {bash_operator.py:122} INFO - Output:
[2020-11-20 23:55:43,575] {bash_operator.py:126} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2020-11-20 23:55:43,581] {bash_operator.py:126} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2020-11-20 23:55:43,697] {bash_operator.py:126} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100    31  100    31    0     0    254      0 --:--:-- --:--:-- --:--:--   256
[2020-11-20 23:55:43,700] {bash_operator.py:130} INFO - Command exited with return code 0
[2020-11-20 23:55:43,725] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=us_covid_daily_report_pipeline, task_id=fetch_covid_daily_recovered, execution_date=20201119T000000, start_date=20201120T235543, end_date=20201120T235543
[2020-11-20 23:55:53,022] {logging_mixin.py:112} INFO - [2020-11-20 23:55:53,021] {local_task_job.py:103} INFO - Task exited with return code 0
